spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
server:
  port: 9080

logging:
  level:
    com.homework.railwayproject: trace

#预留位置整秘钥还有生存时间