spring:
  application:
    name: railwayProject
  servlet:
    multipart:
      max-file-size: 100MB        # 单个文件最大大小
      max-request-size: 100MB     # 整个请求最大大小
      enabled: true
      # 增加超时配置
      file-size-threshold: 10MB   # 文件大小阈值，超过此值将写入磁盘
      location: /tmp              # 临时文件位置

  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  data:
    redis:
      timeout: 2000ms
      port: 6379
      host: localhost
mybatis-plus:
  check-config-location: true
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.homework.railwayproject.pojo.entity

knife4j:
  basic:
    enable: true
  contact:
    name: 谢云轩
    email: 1721476339@qq.com
    url: http://www.baidu.com

app:
  data-version: 1.1